### ISSUE TITLE
JWT Samples in Chapter 7 don't work with new version of jwt-go

### ISSUE THREAD

**Issue by jsuarezm** [shijuvar/go-web#5]
New version of jwt-go is 3.0.0. This current version don't work with the current jwt authentication samples, when I compiled it, the following error was generated:
# command-line-arguments
./main.go:72: invalid operation: t.Claims["iss"] (type jwt.Claims does not support indexing)
./main.go:73: invalid operation: t.Claims["CustomUserInfo"] (type jwt.Claims does not support indexing)
./main.go:79: invalid operation: t.Claims["exp"] (type jwt.Claims does not support indexing)
./main.go:94: undefined: jwt.ParseFromRequest

The workaround used was to delete the jwt-got library from GOPATH source and manually (git clone) download the package and use the version 2.7.0 (checkout tags/v2.7.0 -b jwtauth) and then copy to the GOPATH source.

**Comment by shijuvar** [comment]
Modified the source in order to work with new version of jwt-go.

**Comment by arifmahmudrana** [comment]
@shijuvar I have copied your code to my directory also for keys I copied demo keys to keys directory but when run I get this error

```
# command-line-arguments
./main.go:72: invalid operation: t.Claims["iss"] (type jwt.Claims does not support indexing)
./main.go:73: invalid operation: t.Claims["CustomUserInfo"] (type jwt.Claims does not support indexing)
./main.go:79: invalid operation: t.Claims["exp"] (type jwt.Claims does not support indexing)
./main.go:94: undefined: jwt.ParseFromRequest
```

**Comment by shijuvar** [comment]
I have modified the source code of TaskManager app (https://github.com/shijuvar/go-web/tree/master/taskmanager) in order to working with new API changes in go-jwt. Use this source instead of chapter 7.

**Comment by arifmahmudrana** [comment]
@shijuvar thanks

**Comment by thanhngvpt** [comment]
@shijuvar I still see errors `./main.go:76: invalid operation: t.Claims["iss"] (type jwt.Claims does not support indexing)
./main.go:77: invalid operation: t.Claims["CustomUserInfo"] (type jwt.Claims does not support indexing)
./main.go:83: invalid operation: t.Claims["exp"] (type jwt.Claims does not support indexing)
./main.go:98: undefined: jwt.ParseFromRequest
` Please check it

**Comment by huyntsgs** [comment]
This code only works with v2.0. To update 3.0 pls follow

  token := jwt.New(jwt.SigningMethodRS256)
  claims := make(jwt.MapClaims)
  claims["exp"] = time.Now().Add(time.Hour * time.Duration(1).Unix()
  claims["iat"] = time.Now().Unix()
  claims["userInfo"] = "userInfo"
  token.Claims = claims
